name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'anw10'
        reponame: 'anw10.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitmsg: 'Deployed online'
        cname: www.arsalan.app
        useyarn: true
